#!/bin/bash
#
# Setup ALSA Softvol for MiniDSP
#

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     MiniDSP ALSA Softvol Setup                            ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Step 1: Find MiniDSP audio device
echo -e "${BLUE}[Step 1]${NC} Finding MiniDSP audio device..."
echo ""

# List all audio cards
echo "Available ALSA cards:"
cat /proc/asound/cards
echo ""

# Try to find MiniDSP card
MINIDSP_CARD=""
if grep -i "minidsp\|2x4hd\|ddrc" /proc/asound/cards > /dev/null; then
    MINIDSP_CARD=$(grep -i "minidsp\|2x4hd\|ddrc" /proc/asound/cards | head -1 | awk '{print $1}')
    echo -e "${GREEN}✓${NC} Found MiniDSP card: hw:$MINIDSP_CARD"
    MINIDSP_CARD="hw:$MINIDSP_CARD"
else
    echo -e "${YELLOW}!${NC} Could not auto-detect MiniDSP card"
    echo ""
    read -p "Enter card number or name (e.g., '0' or 'hw:0'): " MINIDSP_CARD
    if [ -z "$MINIDSP_CARD" ]; then
        echo -e "${RED}✗${NC} No card specified, using hw:0 as default"
        MINIDSP_CARD="hw:0"
    fi
    # Normalize to hw:X format
    if [[ ! "$MINIDSP_CARD" =~ ^hw: ]]; then
        MINIDSP_CARD="hw:$MINIDSP_CARD"
    fi
fi
echo ""

# Step 2: Test the card
echo -e "${BLUE}[Step 2]${NC} Testing card: $MINIDSP_CARD"
if aplay -l | grep -q "${MINIDSP_CARD#hw:}"; then
    echo -e "${GREEN}✓${NC} Card is valid"
else
    echo -e "${YELLOW}!${NC} Warning: Card may not exist"
fi
echo ""

# Step 3: Choose control name
echo -e "${BLUE}[Step 3]${NC} Control name configuration"
echo ""
echo "The softvol control name can be:"
echo "  1) 'Digital' (daemon default)"
echo "  2) 'MiniDSP' (more descriptive)"
echo "  3) Custom name"
echo ""
read -p "Choose [1/2/3]: " CHOICE

case $CHOICE in
    2)
        CONTROL_NAME="MiniDSP"
        ;;
    3)
        read -p "Enter custom name: " CONTROL_NAME
        if [ -z "$CONTROL_NAME" ]; then
            CONTROL_NAME="Digital"
        fi
        ;;
    *)
        CONTROL_NAME="Digital"
        ;;
esac

echo "Using control name: $CONTROL_NAME"
echo ""

# Step 4: Generate .asoundrc
echo -e "${BLUE}[Step 4]${NC} Generating ~/.asoundrc configuration"
echo ""

# Backup existing config
if [ -f ~/.asoundrc ]; then
    BACKUP=~/.asoundrc.backup.$(date +%s)
    echo -e "${YELLOW}!${NC} Backing up existing ~/.asoundrc to $BACKUP"
    cp ~/.asoundrc "$BACKUP"
fi

# Determine card index (extract number from hw:X)
CARD_INDEX=${MINIDSP_CARD#hw:}

# Generate the config
cat > ~/.asoundrc << EOF
# MiniDSP Softvol Configuration
# Generated by setup_alsa_softvol.sh on $(date)
#
# This creates a software volume control for MiniDSP that syncs with
# the hardware master volume through the minidsp daemon.

# Softvol plugin for MiniDSP
pcm.minidsp_${CARD_INDEX}_softvol {
    type softvol
    slave.pcm "${MINIDSP_CARD},0"
    control {
        name "${CONTROL_NAME}"
        card ${CARD_INDEX}
    }
    min_dB -127.0
    max_dB 0.0
    resolution 255
}

# Set as default output (optional - uncomment if desired)
# pcm.!default {
#     type plug
#     slave.pcm "minidsp_${CARD_INDEX}_softvol"
# }
#
# ctl.!default {
#     type hw
#     card ${CARD_INDEX}
# }
EOF

echo -e "${GREEN}✓${NC} Created ~/.asoundrc"
echo ""

# Step 5: Verify the control
echo -e "${BLUE}[Step 5]${NC} Verifying ALSA control"
echo ""

# Reload ALSA
echo "Reloading ALSA..."
alsactl restore 2>/dev/null || true
sleep 1

# Check if control exists
if amixer sget "$CONTROL_NAME" 2>/dev/null | grep -q "Playback"; then
    echo -e "${GREEN}✓${NC} Control '$CONTROL_NAME' created successfully!"
    echo ""
    echo "Current state:"
    amixer sget "$CONTROL_NAME"
else
    echo -e "${RED}✗${NC} Control not found yet"
    echo ""
    echo "Try these commands to activate it:"
    echo "  1) alsactl restore"
    echo "  2) amixer sget '$CONTROL_NAME'"
    echo "  3) alsamixer"
fi
echo ""

# Step 6: Test volume control
echo -e "${BLUE}[Step 6]${NC} Testing volume control"
echo ""
echo "Setting volume to -30 dB..."
if amixer sset "$CONTROL_NAME" -- -30dB 2>/dev/null; then
    echo -e "${GREEN}✓${NC} Volume control works!"
    echo ""
    VOL=$(amixer sget "$CONTROL_NAME" | grep -o '\[-\?[0-9.]*dB\]' | head -1)
    echo "Current volume: $VOL"
else
    echo -e "${RED}✗${NC} Could not set volume"
    echo ""
    echo "Troubleshooting:"
    echo "  1) Check: amixer scontrols"
    echo "  2) Try: alsamixer"
    echo "  3) Restart ALSA: sudo alsa force-reload"
fi
echo ""

# Step 7: Configuration summary
echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}Configuration Summary${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Card:         $MINIDSP_CARD"
echo "Control Name: $CONTROL_NAME"
echo "Resolution:   255 (255 levels = 254 intervals of 0.5 dB)"
echo "Range:        -127.0 dB to 0.0 dB"
echo "Config File:  ~/.asoundrc"
echo ""

if [ -f "$BACKUP" ]; then
    echo "Backup:       $BACKUP"
    echo ""
fi

echo -e "${YELLOW}Next Steps:${NC}"
echo ""
echo "1. Start the daemon:"
echo "   ${BLUE}RUST_LOG=debug target/release/minidspd${NC}"
echo ""
echo "2. In another terminal, test volume sync:"
echo "   ${BLUE}amixer set $CONTROL_NAME -- -20.0dB${NC}"
echo "   ${BLUE}amixer set $CONTROL_NAME -- -20.5dB${NC}"
echo "   ${BLUE}amixer set $CONTROL_NAME -- -21.0dB${NC}"
echo ""
echo "3. Watch daemon logs for:"
echo "   • 'ALSA changed: ... sync: true'"
echo "   • 'Synced ALSA -> MiniDSP volume'"
echo "   • 'Quantizing ALSA ...'"
echo ""
echo "4. Test MiniDSP → ALSA:"
echo "   Use hardware volume buttons/remote and watch sync"
echo ""

# Step 8: Optional - Create daemon config
echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}"
read -p "Create daemon config file? [y/N] " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    CONFIG_FILE=~/minidsp-config.toml

    cat > "$CONFIG_FILE" << EOF
# MiniDSP Daemon Configuration
# Generated on $(date)

[http_server]
bind_address = "127.0.0.1:5380"

[alsa_mixer]
enabled = true
card_name = "$MINIDSP_CARD"
control_name = "$CONTROL_NAME"
sync_interval_ms = 100
output_device = "$MINIDSP_CARD"
EOF

    echo -e "${GREEN}✓${NC} Created $CONFIG_FILE"
    echo ""
    echo "To use this config, start daemon with:"
    echo "  ${BLUE}target/release/minidspd --config $CONFIG_FILE${NC}"
    echo ""
else
    echo ""
    echo "Daemon will use built-in defaults (control name: 'Digital')"
    if [ "$CONTROL_NAME" != "Digital" ]; then
        echo -e "${YELLOW}!${NC} Warning: Your control name is '$CONTROL_NAME'"
        echo "  You should create a config file or change control name to 'Digital'"
    fi
    echo ""
fi

echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Setup Complete!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo ""
