#!/usr/bin/env bash
set -ex

OUT=lib.rs
DEST_DIR=../../src/
CEC_REGEX='(libcec|cec|CEC|LIBCEC)_.*'

# If DOCKER env variable is not set, default to "docker"
if [[ $DOCKER == "" ]]; then
    DOCKER="docker"
fi

# Grab libcec header files as they are included in ubuntu
$DOCKER build -t libcec_bindgen .
$DOCKER run --rm libcec_bindgen | tar -xvzf -
echo "These files are generated by bindgen.sh" > usr/README

function generate() {
    bindgen wrapper.h -o ${OUT}.tmp \
    --whitelist-type $CEC_REGEX \
    --whitelist-function $CEC_REGEX \
    --whitelist-var $CEC_REGEX \
    --no-prepend-enum-name \
    --rustfmt-bindings \
    --raw-line='#![allow(non_upper_case_globals)]' \
    --raw-line='#![allow(non_camel_case_types)]' \
    --raw-line='#![allow(non_snake_case)]' \
    --raw-line='#![allow(dead_code)]' \
    --raw-line='' \
    --raw-line='#[link(name = "cec")] extern {}' \
    "$@" \
    -- \
    -I /usr/include/libcec/
}

# Generate version with enums, and capture the enum definitions
generate --rustified-enum $CEC_REGEX
./sed_bindings.py ${OUT}.tmp ${OUT} --outfile_enum ${OUT}.enum
# Generate (safer) version without enums
generate --constified-enum $CEC_REGEX
./sed_bindings.py ${OUT}.tmp ${OUT}

# Copy enums to cec-rs/src/ crate
cp ${OUT}.enum ../../../cec-rs/src/enums.rs

# Cleanup
rm ${OUT}.tmp ${OUT}.enum
mv ${OUT} ${DEST_DIR}/${OUT}