//
// This file is generated by `minidsp-devtools codegen`. DO NOT EDIT.
//
use super::*;
pub mod sym {
    #[allow(dead_code)]
    pub const DC_INP_ALG_1: u16 = 0;
    pub const MONOMUX_194_0NS_10: u16 = 1;
    pub const MONOMUX_194_0NS_11: u16 = 2;
    pub const STEREOMUX_194_0NS_10: u16 = 3;
    pub const STEREOMUX_194_0NS_11: u16 = 4;
    pub const MUTE_NO_SLEW_ALG_7MUTE: u16 = 5;
    pub const MUTE_NO_SLEW_ALG_2MUTE: u16 = 6;
    pub const MUTE_NO_SLEW_ALG_1MUTE: u16 = 7;
    pub const EQ1940_INVERT_1GAIN: u16 = 8;
    pub const EQ1940_INVERT_2GAIN: u16 = 9;
    pub const GAIN_1940_ALG_NS1: u16 = 10;
    pub const GAIN_1940_ALG_NS2: u16 = 11;
    pub const EQ_CH_1_1_1_B0: u16 = 12;
    pub const EQ_CH_1_1_1_B1: u16 = 13;
    pub const EQ_CH_1_1_1_B2: u16 = 14;
    pub const EQ_CH_1_1_1_A1: u16 = 15;
    pub const EQ_CH_1_1_1_A2: u16 = 16;
    pub const EQ_CH_1_1_2_B0: u16 = 17;
    pub const EQ_CH_1_1_2_B1: u16 = 18;
    pub const EQ_CH_1_1_2_B2: u16 = 19;
    pub const EQ_CH_1_1_2_A1: u16 = 20;
    pub const EQ_CH_1_1_2_A2: u16 = 21;
    pub const EQ_CH_1_1_3_B0: u16 = 22;
    pub const EQ_CH_1_1_3_B1: u16 = 23;
    pub const EQ_CH_1_1_3_B2: u16 = 24;
    pub const EQ_CH_1_1_3_A1: u16 = 25;
    pub const EQ_CH_1_1_3_A2: u16 = 26;
    pub const EQ_CH_1_1_4_B0: u16 = 27;
    pub const EQ_CH_1_1_4_B1: u16 = 28;
    pub const EQ_CH_1_1_4_B2: u16 = 29;
    pub const EQ_CH_1_1_4_A1: u16 = 30;
    pub const EQ_CH_1_1_4_A2: u16 = 31;
    pub const EQ_CH_1_1_5_B0: u16 = 32;
    pub const EQ_CH_1_1_5_B1: u16 = 33;
    pub const EQ_CH_1_1_5_B2: u16 = 34;
    pub const EQ_CH_1_1_5_A1: u16 = 35;
    pub const EQ_CH_1_1_5_A2: u16 = 36;
    pub const EQ_CH_1_1_6_B0: u16 = 37;
    pub const EQ_CH_1_1_6_B1: u16 = 38;
    pub const EQ_CH_1_1_6_B2: u16 = 39;
    pub const EQ_CH_1_1_6_A1: u16 = 40;
    pub const EQ_CH_1_1_6_A2: u16 = 41;
    pub const EQ_CH_2_1_1_B0: u16 = 42;
    pub const EQ_CH_2_1_1_B1: u16 = 43;
    pub const EQ_CH_2_1_1_B2: u16 = 44;
    pub const EQ_CH_2_1_1_A1: u16 = 45;
    pub const EQ_CH_2_1_1_A2: u16 = 46;
    pub const EQ_CH_2_1_2_B0: u16 = 47;
    pub const EQ_CH_2_1_2_B1: u16 = 48;
    pub const EQ_CH_2_1_2_B2: u16 = 49;
    pub const EQ_CH_2_1_2_A1: u16 = 50;
    pub const EQ_CH_2_1_2_A2: u16 = 51;
    pub const EQ_CH_2_1_3_B0: u16 = 52;
    pub const EQ_CH_2_1_3_B1: u16 = 53;
    pub const EQ_CH_2_1_3_B2: u16 = 54;
    pub const EQ_CH_2_1_3_A1: u16 = 55;
    pub const EQ_CH_2_1_3_A2: u16 = 56;
    pub const EQ_CH_2_1_4_B0: u16 = 57;
    pub const EQ_CH_2_1_4_B1: u16 = 58;
    pub const EQ_CH_2_1_4_B2: u16 = 59;
    pub const EQ_CH_2_1_4_A1: u16 = 60;
    pub const EQ_CH_2_1_4_A2: u16 = 61;
    pub const EQ_CH_2_1_5_B0: u16 = 62;
    pub const EQ_CH_2_1_5_B1: u16 = 63;
    pub const EQ_CH_2_1_5_B2: u16 = 64;
    pub const EQ_CH_2_1_5_A1: u16 = 65;
    pub const EQ_CH_2_1_5_A2: u16 = 66;
    pub const EQ_CH_2_1_6_B0: u16 = 67;
    pub const EQ_CH_2_1_6_B1: u16 = 68;
    pub const EQ_CH_2_1_6_B2: u16 = 69;
    pub const EQ_CH_2_1_6_A1: u16 = 70;
    pub const EQ_CH_2_1_6_A2: u16 = 71;
    pub const EQ_CH_2_5_1_B0: u16 = 72;
    pub const EQ_CH_2_5_1_B1: u16 = 73;
    pub const EQ_CH_2_5_1_B2: u16 = 74;
    pub const EQ_CH_2_5_1_A1: u16 = 75;
    pub const EQ_CH_2_5_1_A2: u16 = 76;
    pub const EQ_CH_2_5_2_B0: u16 = 77;
    pub const EQ_CH_2_5_2_B1: u16 = 78;
    pub const EQ_CH_2_5_2_B2: u16 = 79;
    pub const EQ_CH_2_5_2_A1: u16 = 80;
    pub const EQ_CH_2_5_2_A2: u16 = 81;
    pub const EQ_CH_2_5_3_B0: u16 = 82;
    pub const EQ_CH_2_5_3_B1: u16 = 83;
    pub const EQ_CH_2_5_3_B2: u16 = 84;
    pub const EQ_CH_2_5_3_A1: u16 = 85;
    pub const EQ_CH_2_5_3_A2: u16 = 86;
    pub const EQ_CH_2_5_4_B0: u16 = 87;
    pub const EQ_CH_2_5_4_B1: u16 = 88;
    pub const EQ_CH_2_5_4_B2: u16 = 89;
    pub const EQ_CH_2_5_4_A1: u16 = 90;
    pub const EQ_CH_2_5_4_A2: u16 = 91;
    pub const EQ_CH_2_5_5_B0: u16 = 92;
    pub const EQ_CH_2_5_5_B1: u16 = 93;
    pub const EQ_CH_2_5_5_B2: u16 = 94;
    pub const EQ_CH_2_5_5_A1: u16 = 95;
    pub const EQ_CH_2_5_5_A2: u16 = 96;
    pub const EQ_CH_2_5_6_B0: u16 = 97;
    pub const EQ_CH_2_5_6_B1: u16 = 98;
    pub const EQ_CH_2_5_6_B2: u16 = 99;
    pub const EQ_CH_2_5_6_A1: u16 = 100;
    pub const EQ_CH_2_5_6_A2: u16 = 101;
    pub const EQ_CH_2_5_7_B0: u16 = 102;
    pub const EQ_CH_2_5_7_B1: u16 = 103;
    pub const EQ_CH_2_5_7_B2: u16 = 104;
    pub const EQ_CH_2_5_7_A1: u16 = 105;
    pub const EQ_CH_2_5_7_A2: u16 = 106;
    pub const EQ_CH_2_5_8_B0: u16 = 107;
    pub const EQ_CH_2_5_8_B1: u16 = 108;
    pub const EQ_CH_2_5_8_B2: u16 = 109;
    pub const EQ_CH_2_5_8_A1: u16 = 110;
    pub const EQ_CH_2_5_8_A2: u16 = 111;
    pub const EQ_CH_1_4_1_B0: u16 = 112;
    pub const EQ_CH_1_4_1_B1: u16 = 113;
    pub const EQ_CH_1_4_1_B2: u16 = 114;
    pub const EQ_CH_1_4_1_A1: u16 = 115;
    pub const EQ_CH_1_4_1_A2: u16 = 116;
    pub const EQ_CH_1_4_2_B0: u16 = 117;
    pub const EQ_CH_1_4_2_B1: u16 = 118;
    pub const EQ_CH_1_4_2_B2: u16 = 119;
    pub const EQ_CH_1_4_2_A1: u16 = 120;
    pub const EQ_CH_1_4_2_A2: u16 = 121;
    pub const EQ_CH_1_4_3_B0: u16 = 122;
    pub const EQ_CH_1_4_3_B1: u16 = 123;
    pub const EQ_CH_1_4_3_B2: u16 = 124;
    pub const EQ_CH_1_4_3_A1: u16 = 125;
    pub const EQ_CH_1_4_3_A2: u16 = 126;
    pub const EQ_CH_1_4_4_B0: u16 = 127;
    pub const EQ_CH_1_4_4_B1: u16 = 128;
    pub const EQ_CH_1_4_4_B2: u16 = 129;
    pub const EQ_CH_1_4_4_A1: u16 = 130;
    pub const EQ_CH_1_4_4_A2: u16 = 131;
    pub const EQ_CH_1_4_5_B0: u16 = 132;
    pub const EQ_CH_1_4_5_B1: u16 = 133;
    pub const EQ_CH_1_4_5_B2: u16 = 134;
    pub const EQ_CH_1_4_5_A1: u16 = 135;
    pub const EQ_CH_1_4_5_A2: u16 = 136;
    pub const EQ_CH_1_4_6_B0: u16 = 137;
    pub const EQ_CH_1_4_6_B1: u16 = 138;
    pub const EQ_CH_1_4_6_B2: u16 = 139;
    pub const EQ_CH_1_4_6_A1: u16 = 140;
    pub const EQ_CH_1_4_6_A2: u16 = 141;
    pub const EQ_CH_1_4_7_B0: u16 = 142;
    pub const EQ_CH_1_4_7_B1: u16 = 143;
    pub const EQ_CH_1_4_7_B2: u16 = 144;
    pub const EQ_CH_1_4_7_A1: u16 = 145;
    pub const EQ_CH_1_4_7_A2: u16 = 146;
    pub const EQ_CH_1_4_8_B0: u16 = 147;
    pub const EQ_CH_1_4_8_B1: u16 = 148;
    pub const EQ_CH_1_4_8_B2: u16 = 149;
    pub const EQ_CH_1_4_8_A1: u16 = 150;
    pub const EQ_CH_1_4_8_A2: u16 = 151;
    pub const EQ_CH_1_5_1_B0: u16 = 152;
    pub const EQ_CH_1_5_1_B1: u16 = 153;
    pub const EQ_CH_1_5_1_B2: u16 = 154;
    pub const EQ_CH_1_5_1_A1: u16 = 155;
    pub const EQ_CH_1_5_1_A2: u16 = 156;
    pub const EQ_CH_1_5_2_B0: u16 = 157;
    pub const EQ_CH_1_5_2_B1: u16 = 158;
    pub const EQ_CH_1_5_2_B2: u16 = 159;
    pub const EQ_CH_1_5_2_A1: u16 = 160;
    pub const EQ_CH_1_5_2_A2: u16 = 161;
    pub const EQ_CH_1_5_3_B0: u16 = 162;
    pub const EQ_CH_1_5_3_B1: u16 = 163;
    pub const EQ_CH_1_5_3_B2: u16 = 164;
    pub const EQ_CH_1_5_3_A1: u16 = 165;
    pub const EQ_CH_1_5_3_A2: u16 = 166;
    pub const EQ_CH_1_5_4_B0: u16 = 167;
    pub const EQ_CH_1_5_4_B1: u16 = 168;
    pub const EQ_CH_1_5_4_B2: u16 = 169;
    pub const EQ_CH_1_5_4_A1: u16 = 170;
    pub const EQ_CH_1_5_4_A2: u16 = 171;
    pub const EQ_CH_1_5_5_B0: u16 = 172;
    pub const EQ_CH_1_5_5_B1: u16 = 173;
    pub const EQ_CH_1_5_5_B2: u16 = 174;
    pub const EQ_CH_1_5_5_A1: u16 = 175;
    pub const EQ_CH_1_5_5_A2: u16 = 176;
    pub const EQ_CH_1_5_6_B0: u16 = 177;
    pub const EQ_CH_1_5_6_B1: u16 = 178;
    pub const EQ_CH_1_5_6_B2: u16 = 179;
    pub const EQ_CH_1_5_6_A1: u16 = 180;
    pub const EQ_CH_1_5_6_A2: u16 = 181;
    pub const EQ_CH_1_5_7_B0: u16 = 182;
    pub const EQ_CH_1_5_7_B1: u16 = 183;
    pub const EQ_CH_1_5_7_B2: u16 = 184;
    pub const EQ_CH_1_5_7_A1: u16 = 185;
    pub const EQ_CH_1_5_7_A2: u16 = 186;
    pub const EQ_CH_1_5_8_B0: u16 = 187;
    pub const EQ_CH_1_5_8_B1: u16 = 188;
    pub const EQ_CH_1_5_8_B2: u16 = 189;
    pub const EQ_CH_1_5_8_A1: u16 = 190;
    pub const EQ_CH_1_5_8_A2: u16 = 191;
    pub const EQ_CH_2_4_1_B0: u16 = 192;
    pub const EQ_CH_2_4_1_B1: u16 = 193;
    pub const EQ_CH_2_4_1_B2: u16 = 194;
    pub const EQ_CH_2_4_1_A1: u16 = 195;
    pub const EQ_CH_2_4_1_A2: u16 = 196;
    pub const EQ_CH_2_4_2_B0: u16 = 197;
    pub const EQ_CH_2_4_2_B1: u16 = 198;
    pub const EQ_CH_2_4_2_B2: u16 = 199;
    pub const EQ_CH_2_4_2_A1: u16 = 200;
    pub const EQ_CH_2_4_2_A2: u16 = 201;
    pub const EQ_CH_2_4_3_B0: u16 = 202;
    pub const EQ_CH_2_4_3_B1: u16 = 203;
    pub const EQ_CH_2_4_3_B2: u16 = 204;
    pub const EQ_CH_2_4_3_A1: u16 = 205;
    pub const EQ_CH_2_4_3_A2: u16 = 206;
    pub const EQ_CH_2_4_4_B0: u16 = 207;
    pub const EQ_CH_2_4_4_B1: u16 = 208;
    pub const EQ_CH_2_4_4_B2: u16 = 209;
    pub const EQ_CH_2_4_4_A1: u16 = 210;
    pub const EQ_CH_2_4_4_A2: u16 = 211;
    pub const EQ_CH_2_4_5_B0: u16 = 212;
    pub const EQ_CH_2_4_5_B1: u16 = 213;
    pub const EQ_CH_2_4_5_B2: u16 = 214;
    pub const EQ_CH_2_4_5_A1: u16 = 215;
    pub const EQ_CH_2_4_5_A2: u16 = 216;
    pub const EQ_CH_2_4_6_B0: u16 = 217;
    pub const EQ_CH_2_4_6_B1: u16 = 218;
    pub const EQ_CH_2_4_6_B2: u16 = 219;
    pub const EQ_CH_2_4_6_A1: u16 = 220;
    pub const EQ_CH_2_4_6_A2: u16 = 221;
    pub const EQ_CH_2_4_7_B0: u16 = 222;
    pub const EQ_CH_2_4_7_B1: u16 = 223;
    pub const EQ_CH_2_4_7_B2: u16 = 224;
    pub const EQ_CH_2_4_7_A1: u16 = 225;
    pub const EQ_CH_2_4_7_A2: u16 = 226;
    pub const EQ_CH_2_4_8_B0: u16 = 227;
    pub const EQ_CH_2_4_8_B1: u16 = 228;
    pub const EQ_CH_2_4_8_B2: u16 = 229;
    pub const EQ_CH_2_4_8_A1: u16 = 230;
    pub const EQ_CH_2_4_8_A2: u16 = 231;
    pub const EQ_CH_1_3_1_B0: u16 = 232;
    pub const EQ_CH_1_3_1_B1: u16 = 233;
    pub const EQ_CH_1_3_1_B2: u16 = 234;
    pub const EQ_CH_1_3_1_A1: u16 = 235;
    pub const EQ_CH_1_3_1_A2: u16 = 236;
    pub const EQ_CH_1_3_2_B0: u16 = 237;
    pub const EQ_CH_1_3_2_B1: u16 = 238;
    pub const EQ_CH_1_3_2_B2: u16 = 239;
    pub const EQ_CH_1_3_2_A1: u16 = 240;
    pub const EQ_CH_1_3_2_A2: u16 = 241;
    pub const EQ_CH_1_3_3_B0: u16 = 242;
    pub const EQ_CH_1_3_3_B1: u16 = 243;
    pub const EQ_CH_1_3_3_B2: u16 = 244;
    pub const EQ_CH_1_3_3_A1: u16 = 245;
    pub const EQ_CH_1_3_3_A2: u16 = 246;
    pub const EQ_CH_1_3_4_B0: u16 = 247;
    pub const EQ_CH_1_3_4_B1: u16 = 248;
    pub const EQ_CH_1_3_4_B2: u16 = 249;
    pub const EQ_CH_1_3_4_A1: u16 = 250;
    pub const EQ_CH_1_3_4_A2: u16 = 251;
    pub const EQ_CH_1_3_5_B0: u16 = 252;
    pub const EQ_CH_1_3_5_B1: u16 = 253;
    pub const EQ_CH_1_3_5_B2: u16 = 254;
    pub const EQ_CH_1_3_5_A1: u16 = 255;
    pub const EQ_CH_1_3_5_A2: u16 = 256;
    pub const EQ_CH_1_3_6_B0: u16 = 257;
    pub const EQ_CH_1_3_6_B1: u16 = 258;
    pub const EQ_CH_1_3_6_B2: u16 = 259;
    pub const EQ_CH_1_3_6_A1: u16 = 260;
    pub const EQ_CH_1_3_6_A2: u16 = 261;
    pub const EQ_CH_2_3_1_B0: u16 = 262;
    pub const EQ_CH_2_3_1_B1: u16 = 263;
    pub const EQ_CH_2_3_1_B2: u16 = 264;
    pub const EQ_CH_2_3_1_A1: u16 = 265;
    pub const EQ_CH_2_3_1_A2: u16 = 266;
    pub const EQ_CH_2_3_2_B0: u16 = 267;
    pub const EQ_CH_2_3_2_B1: u16 = 268;
    pub const EQ_CH_2_3_2_B2: u16 = 269;
    pub const EQ_CH_2_3_2_A1: u16 = 270;
    pub const EQ_CH_2_3_2_A2: u16 = 271;
    pub const EQ_CH_2_3_3_B0: u16 = 272;
    pub const EQ_CH_2_3_3_B1: u16 = 273;
    pub const EQ_CH_2_3_3_B2: u16 = 274;
    pub const EQ_CH_2_3_3_A1: u16 = 275;
    pub const EQ_CH_2_3_3_A2: u16 = 276;
    pub const EQ_CH_2_3_4_B0: u16 = 277;
    pub const EQ_CH_2_3_4_B1: u16 = 278;
    pub const EQ_CH_2_3_4_B2: u16 = 279;
    pub const EQ_CH_2_3_4_A1: u16 = 280;
    pub const EQ_CH_2_3_4_A2: u16 = 281;
    pub const EQ_CH_2_3_5_B0: u16 = 282;
    pub const EQ_CH_2_3_5_B1: u16 = 283;
    pub const EQ_CH_2_3_5_B2: u16 = 284;
    pub const EQ_CH_2_3_5_A1: u16 = 285;
    pub const EQ_CH_2_3_5_A2: u16 = 286;
    pub const EQ_CH_2_3_6_B0: u16 = 287;
    pub const EQ_CH_2_3_6_B1: u16 = 288;
    pub const EQ_CH_2_3_6_B2: u16 = 289;
    pub const EQ_CH_2_3_6_A1: u16 = 290;
    pub const EQ_CH_2_3_6_A2: u16 = 291;
    pub const EQ_CH_2_2_1_B0: u16 = 292;
    pub const EQ_CH_2_2_1_B1: u16 = 293;
    pub const EQ_CH_2_2_1_B2: u16 = 294;
    pub const EQ_CH_2_2_1_A1: u16 = 295;
    pub const EQ_CH_2_2_1_A2: u16 = 296;
    pub const EQ_CH_2_2_2_B0: u16 = 297;
    pub const EQ_CH_2_2_2_B1: u16 = 298;
    pub const EQ_CH_2_2_2_B2: u16 = 299;
    pub const EQ_CH_2_2_2_A1: u16 = 300;
    pub const EQ_CH_2_2_2_A2: u16 = 301;
    pub const EQ_CH_2_2_3_B0: u16 = 302;
    pub const EQ_CH_2_2_3_B1: u16 = 303;
    pub const EQ_CH_2_2_3_B2: u16 = 304;
    pub const EQ_CH_2_2_3_A1: u16 = 305;
    pub const EQ_CH_2_2_3_A2: u16 = 306;
    pub const EQ_CH_2_2_4_B0: u16 = 307;
    pub const EQ_CH_2_2_4_B1: u16 = 308;
    pub const EQ_CH_2_2_4_B2: u16 = 309;
    pub const EQ_CH_2_2_4_A1: u16 = 310;
    pub const EQ_CH_2_2_4_A2: u16 = 311;
    pub const EQ_CH_2_2_5_B0: u16 = 312;
    pub const EQ_CH_2_2_5_B1: u16 = 313;
    pub const EQ_CH_2_2_5_B2: u16 = 314;
    pub const EQ_CH_2_2_5_A1: u16 = 315;
    pub const EQ_CH_2_2_5_A2: u16 = 316;
    pub const EQ_CH_2_2_6_B0: u16 = 317;
    pub const EQ_CH_2_2_6_B1: u16 = 318;
    pub const EQ_CH_2_2_6_B2: u16 = 319;
    pub const EQ_CH_2_2_6_A1: u16 = 320;
    pub const EQ_CH_2_2_6_A2: u16 = 321;
    pub const EQ_CH_1_2_1_B0: u16 = 322;
    pub const EQ_CH_1_2_1_B1: u16 = 323;
    pub const EQ_CH_1_2_1_B2: u16 = 324;
    pub const EQ_CH_1_2_1_A1: u16 = 325;
    pub const EQ_CH_1_2_1_A2: u16 = 326;
    pub const EQ_CH_1_2_2_B0: u16 = 327;
    pub const EQ_CH_1_2_2_B1: u16 = 328;
    pub const EQ_CH_1_2_2_B2: u16 = 329;
    pub const EQ_CH_1_2_2_A1: u16 = 330;
    pub const EQ_CH_1_2_2_A2: u16 = 331;
    pub const EQ_CH_1_2_3_B0: u16 = 332;
    pub const EQ_CH_1_2_3_B1: u16 = 333;
    pub const EQ_CH_1_2_3_B2: u16 = 334;
    pub const EQ_CH_1_2_3_A1: u16 = 335;
    pub const EQ_CH_1_2_3_A2: u16 = 336;
    pub const EQ_CH_1_2_4_B0: u16 = 337;
    pub const EQ_CH_1_2_4_B1: u16 = 338;
    pub const EQ_CH_1_2_4_B2: u16 = 339;
    pub const EQ_CH_1_2_4_A1: u16 = 340;
    pub const EQ_CH_1_2_4_A2: u16 = 341;
    pub const EQ_CH_1_2_5_B0: u16 = 342;
    pub const EQ_CH_1_2_5_B1: u16 = 343;
    pub const EQ_CH_1_2_5_B2: u16 = 344;
    pub const EQ_CH_1_2_5_A1: u16 = 345;
    pub const EQ_CH_1_2_5_A2: u16 = 346;
    pub const EQ_CH_1_2_6_B0: u16 = 347;
    pub const EQ_CH_1_2_6_B1: u16 = 348;
    pub const EQ_CH_1_2_6_B2: u16 = 349;
    pub const EQ_CH_1_2_6_A1: u16 = 350;
    pub const EQ_CH_1_2_6_A2: u16 = 351;
    pub const MULT_CTRL_DEL_GROW_ALG_4: u16 = 352;
    pub const MULT_CTRL_DEL_GROW_ALG_3: u16 = 353;
    pub const MULT_CTRL_DEL_GROW_ALG_1: u16 = 354;
    pub const MULT_CTRL_DEL_GROW_ALG_2: u16 = 355;
    pub const GAIN_1940_ALG_NS6: u16 = 356;
    pub const GAIN_1940_ALG_NS3: u16 = 357;
    pub const GAIN_1940_ALG_NS5: u16 = 358;
    pub const GAIN_1940_ALG_NS4: u16 = 359;
    pub const MUTE_NO_SLEW_ALG_5MUTE: u16 = 360;
    pub const MUTE_NO_SLEW_ALG_3MUTE: u16 = 361;
    pub const MUTE_NO_SLEW_ALG_6MUTE: u16 = 362;
    pub const MUTE_NO_SLEW_ALG_4MUTE: u16 = 363;
    pub const EQ1940_INVERT_4GAIN: u16 = 364;
    pub const EQ1940_INVERT_5GAIN: u16 = 365;
    pub const EQ1940_INVERT_3GAIN: u16 = 366;
    pub const EQ1940_INVERT_6GAIN: u16 = 367;
    pub const EXT_SW_GAIN_DB_1STEP: u16 = 368;
    pub const STEREO_DEMUX_SLEW_10: u16 = 369;
    pub const STEREO_DEMUX_SLEW_11: u16 = 370;
    pub const SINGLE_CTRL_MIXER_NEW19401: u16 = 371;
    pub const ST_MUX_SW_SLEW_1COEFFNAME: u16 = 372;
    pub const STEREOMUX_194_0NS_20: u16 = 373;
    pub const STEREOMUX_194_0NS_21: u16 = 374;
    pub const STEREOMUX_194_0NS_22: u16 = 375;
    pub const DC_BLOCK_ALG_DOUBLE_PREC_1POLE: u16 = 376;
    pub const DC_BLOCK_ALG_DOUBLE_PREC_2POLE: u16 = 377;
    pub const MONO_ENVELOPE_PEAK_ALG_1HOLD: u16 = 378;
    pub const MONO_ENVELOPE_PEAK_ALG_1DECAY: u16 = 379;
    pub const MONO_ENVELOPE_PEAK_ALG_2HOLD: u16 = 380;
    pub const MONO_ENVELOPE_PEAK_ALG_2DECAY: u16 = 381;
    #[cfg(feature = "symbols")]
    pub const SYMBOLS: &[(&str, u16)] = &[
        ("DC_INP_ALG_1", DC_INP_ALG_1),
        ("MONOMUX_194_0NS_10", MONOMUX_194_0NS_10),
        ("MONOMUX_194_0NS_11", MONOMUX_194_0NS_11),
        ("STEREOMUX_194_0NS_10", STEREOMUX_194_0NS_10),
        ("STEREOMUX_194_0NS_11", STEREOMUX_194_0NS_11),
        ("MUTE_NO_SLEW_ALG_7MUTE", MUTE_NO_SLEW_ALG_7MUTE),
        ("MUTE_NO_SLEW_ALG_2MUTE", MUTE_NO_SLEW_ALG_2MUTE),
        ("MUTE_NO_SLEW_ALG_1MUTE", MUTE_NO_SLEW_ALG_1MUTE),
        ("EQ1940_INVERT_1GAIN", EQ1940_INVERT_1GAIN),
        ("EQ1940_INVERT_2GAIN", EQ1940_INVERT_2GAIN),
        ("GAIN_1940_ALG_NS1", GAIN_1940_ALG_NS1),
        ("GAIN_1940_ALG_NS2", GAIN_1940_ALG_NS2),
        ("EQ_CH_1_1_1_B0", EQ_CH_1_1_1_B0),
        ("EQ_CH_1_1_1_B1", EQ_CH_1_1_1_B1),
        ("EQ_CH_1_1_1_B2", EQ_CH_1_1_1_B2),
        ("EQ_CH_1_1_1_A1", EQ_CH_1_1_1_A1),
        ("EQ_CH_1_1_1_A2", EQ_CH_1_1_1_A2),
        ("EQ_CH_1_1_2_B0", EQ_CH_1_1_2_B0),
        ("EQ_CH_1_1_2_B1", EQ_CH_1_1_2_B1),
        ("EQ_CH_1_1_2_B2", EQ_CH_1_1_2_B2),
        ("EQ_CH_1_1_2_A1", EQ_CH_1_1_2_A1),
        ("EQ_CH_1_1_2_A2", EQ_CH_1_1_2_A2),
        ("EQ_CH_1_1_3_B0", EQ_CH_1_1_3_B0),
        ("EQ_CH_1_1_3_B1", EQ_CH_1_1_3_B1),
        ("EQ_CH_1_1_3_B2", EQ_CH_1_1_3_B2),
        ("EQ_CH_1_1_3_A1", EQ_CH_1_1_3_A1),
        ("EQ_CH_1_1_3_A2", EQ_CH_1_1_3_A2),
        ("EQ_CH_1_1_4_B0", EQ_CH_1_1_4_B0),
        ("EQ_CH_1_1_4_B1", EQ_CH_1_1_4_B1),
        ("EQ_CH_1_1_4_B2", EQ_CH_1_1_4_B2),
        ("EQ_CH_1_1_4_A1", EQ_CH_1_1_4_A1),
        ("EQ_CH_1_1_4_A2", EQ_CH_1_1_4_A2),
        ("EQ_CH_1_1_5_B0", EQ_CH_1_1_5_B0),
        ("EQ_CH_1_1_5_B1", EQ_CH_1_1_5_B1),
        ("EQ_CH_1_1_5_B2", EQ_CH_1_1_5_B2),
        ("EQ_CH_1_1_5_A1", EQ_CH_1_1_5_A1),
        ("EQ_CH_1_1_5_A2", EQ_CH_1_1_5_A2),
        ("EQ_CH_1_1_6_B0", EQ_CH_1_1_6_B0),
        ("EQ_CH_1_1_6_B1", EQ_CH_1_1_6_B1),
        ("EQ_CH_1_1_6_B2", EQ_CH_1_1_6_B2),
        ("EQ_CH_1_1_6_A1", EQ_CH_1_1_6_A1),
        ("EQ_CH_1_1_6_A2", EQ_CH_1_1_6_A2),
        ("EQ_CH_2_1_1_B0", EQ_CH_2_1_1_B0),
        ("EQ_CH_2_1_1_B1", EQ_CH_2_1_1_B1),
        ("EQ_CH_2_1_1_B2", EQ_CH_2_1_1_B2),
        ("EQ_CH_2_1_1_A1", EQ_CH_2_1_1_A1),
        ("EQ_CH_2_1_1_A2", EQ_CH_2_1_1_A2),
        ("EQ_CH_2_1_2_B0", EQ_CH_2_1_2_B0),
        ("EQ_CH_2_1_2_B1", EQ_CH_2_1_2_B1),
        ("EQ_CH_2_1_2_B2", EQ_CH_2_1_2_B2),
        ("EQ_CH_2_1_2_A1", EQ_CH_2_1_2_A1),
        ("EQ_CH_2_1_2_A2", EQ_CH_2_1_2_A2),
        ("EQ_CH_2_1_3_B0", EQ_CH_2_1_3_B0),
        ("EQ_CH_2_1_3_B1", EQ_CH_2_1_3_B1),
        ("EQ_CH_2_1_3_B2", EQ_CH_2_1_3_B2),
        ("EQ_CH_2_1_3_A1", EQ_CH_2_1_3_A1),
        ("EQ_CH_2_1_3_A2", EQ_CH_2_1_3_A2),
        ("EQ_CH_2_1_4_B0", EQ_CH_2_1_4_B0),
        ("EQ_CH_2_1_4_B1", EQ_CH_2_1_4_B1),
        ("EQ_CH_2_1_4_B2", EQ_CH_2_1_4_B2),
        ("EQ_CH_2_1_4_A1", EQ_CH_2_1_4_A1),
        ("EQ_CH_2_1_4_A2", EQ_CH_2_1_4_A2),
        ("EQ_CH_2_1_5_B0", EQ_CH_2_1_5_B0),
        ("EQ_CH_2_1_5_B1", EQ_CH_2_1_5_B1),
        ("EQ_CH_2_1_5_B2", EQ_CH_2_1_5_B2),
        ("EQ_CH_2_1_5_A1", EQ_CH_2_1_5_A1),
        ("EQ_CH_2_1_5_A2", EQ_CH_2_1_5_A2),
        ("EQ_CH_2_1_6_B0", EQ_CH_2_1_6_B0),
        ("EQ_CH_2_1_6_B1", EQ_CH_2_1_6_B1),
        ("EQ_CH_2_1_6_B2", EQ_CH_2_1_6_B2),
        ("EQ_CH_2_1_6_A1", EQ_CH_2_1_6_A1),
        ("EQ_CH_2_1_6_A2", EQ_CH_2_1_6_A2),
        ("EQ_CH_2_5_1_B0", EQ_CH_2_5_1_B0),
        ("EQ_CH_2_5_1_B1", EQ_CH_2_5_1_B1),
        ("EQ_CH_2_5_1_B2", EQ_CH_2_5_1_B2),
        ("EQ_CH_2_5_1_A1", EQ_CH_2_5_1_A1),
        ("EQ_CH_2_5_1_A2", EQ_CH_2_5_1_A2),
        ("EQ_CH_2_5_2_B0", EQ_CH_2_5_2_B0),
        ("EQ_CH_2_5_2_B1", EQ_CH_2_5_2_B1),
        ("EQ_CH_2_5_2_B2", EQ_CH_2_5_2_B2),
        ("EQ_CH_2_5_2_A1", EQ_CH_2_5_2_A1),
        ("EQ_CH_2_5_2_A2", EQ_CH_2_5_2_A2),
        ("EQ_CH_2_5_3_B0", EQ_CH_2_5_3_B0),
        ("EQ_CH_2_5_3_B1", EQ_CH_2_5_3_B1),
        ("EQ_CH_2_5_3_B2", EQ_CH_2_5_3_B2),
        ("EQ_CH_2_5_3_A1", EQ_CH_2_5_3_A1),
        ("EQ_CH_2_5_3_A2", EQ_CH_2_5_3_A2),
        ("EQ_CH_2_5_4_B0", EQ_CH_2_5_4_B0),
        ("EQ_CH_2_5_4_B1", EQ_CH_2_5_4_B1),
        ("EQ_CH_2_5_4_B2", EQ_CH_2_5_4_B2),
        ("EQ_CH_2_5_4_A1", EQ_CH_2_5_4_A1),
        ("EQ_CH_2_5_4_A2", EQ_CH_2_5_4_A2),
        ("EQ_CH_2_5_5_B0", EQ_CH_2_5_5_B0),
        ("EQ_CH_2_5_5_B1", EQ_CH_2_5_5_B1),
        ("EQ_CH_2_5_5_B2", EQ_CH_2_5_5_B2),
        ("EQ_CH_2_5_5_A1", EQ_CH_2_5_5_A1),
        ("EQ_CH_2_5_5_A2", EQ_CH_2_5_5_A2),
        ("EQ_CH_2_5_6_B0", EQ_CH_2_5_6_B0),
        ("EQ_CH_2_5_6_B1", EQ_CH_2_5_6_B1),
        ("EQ_CH_2_5_6_B2", EQ_CH_2_5_6_B2),
        ("EQ_CH_2_5_6_A1", EQ_CH_2_5_6_A1),
        ("EQ_CH_2_5_6_A2", EQ_CH_2_5_6_A2),
        ("EQ_CH_2_5_7_B0", EQ_CH_2_5_7_B0),
        ("EQ_CH_2_5_7_B1", EQ_CH_2_5_7_B1),
        ("EQ_CH_2_5_7_B2", EQ_CH_2_5_7_B2),
        ("EQ_CH_2_5_7_A1", EQ_CH_2_5_7_A1),
        ("EQ_CH_2_5_7_A2", EQ_CH_2_5_7_A2),
        ("EQ_CH_2_5_8_B0", EQ_CH_2_5_8_B0),
        ("EQ_CH_2_5_8_B1", EQ_CH_2_5_8_B1),
        ("EQ_CH_2_5_8_B2", EQ_CH_2_5_8_B2),
        ("EQ_CH_2_5_8_A1", EQ_CH_2_5_8_A1),
        ("EQ_CH_2_5_8_A2", EQ_CH_2_5_8_A2),
        ("EQ_CH_1_4_1_B0", EQ_CH_1_4_1_B0),
        ("EQ_CH_1_4_1_B1", EQ_CH_1_4_1_B1),
        ("EQ_CH_1_4_1_B2", EQ_CH_1_4_1_B2),
        ("EQ_CH_1_4_1_A1", EQ_CH_1_4_1_A1),
        ("EQ_CH_1_4_1_A2", EQ_CH_1_4_1_A2),
        ("EQ_CH_1_4_2_B0", EQ_CH_1_4_2_B0),
        ("EQ_CH_1_4_2_B1", EQ_CH_1_4_2_B1),
        ("EQ_CH_1_4_2_B2", EQ_CH_1_4_2_B2),
        ("EQ_CH_1_4_2_A1", EQ_CH_1_4_2_A1),
        ("EQ_CH_1_4_2_A2", EQ_CH_1_4_2_A2),
        ("EQ_CH_1_4_3_B0", EQ_CH_1_4_3_B0),
        ("EQ_CH_1_4_3_B1", EQ_CH_1_4_3_B1),
        ("EQ_CH_1_4_3_B2", EQ_CH_1_4_3_B2),
        ("EQ_CH_1_4_3_A1", EQ_CH_1_4_3_A1),
        ("EQ_CH_1_4_3_A2", EQ_CH_1_4_3_A2),
        ("EQ_CH_1_4_4_B0", EQ_CH_1_4_4_B0),
        ("EQ_CH_1_4_4_B1", EQ_CH_1_4_4_B1),
        ("EQ_CH_1_4_4_B2", EQ_CH_1_4_4_B2),
        ("EQ_CH_1_4_4_A1", EQ_CH_1_4_4_A1),
        ("EQ_CH_1_4_4_A2", EQ_CH_1_4_4_A2),
        ("EQ_CH_1_4_5_B0", EQ_CH_1_4_5_B0),
        ("EQ_CH_1_4_5_B1", EQ_CH_1_4_5_B1),
        ("EQ_CH_1_4_5_B2", EQ_CH_1_4_5_B2),
        ("EQ_CH_1_4_5_A1", EQ_CH_1_4_5_A1),
        ("EQ_CH_1_4_5_A2", EQ_CH_1_4_5_A2),
        ("EQ_CH_1_4_6_B0", EQ_CH_1_4_6_B0),
        ("EQ_CH_1_4_6_B1", EQ_CH_1_4_6_B1),
        ("EQ_CH_1_4_6_B2", EQ_CH_1_4_6_B2),
        ("EQ_CH_1_4_6_A1", EQ_CH_1_4_6_A1),
        ("EQ_CH_1_4_6_A2", EQ_CH_1_4_6_A2),
        ("EQ_CH_1_4_7_B0", EQ_CH_1_4_7_B0),
        ("EQ_CH_1_4_7_B1", EQ_CH_1_4_7_B1),
        ("EQ_CH_1_4_7_B2", EQ_CH_1_4_7_B2),
        ("EQ_CH_1_4_7_A1", EQ_CH_1_4_7_A1),
        ("EQ_CH_1_4_7_A2", EQ_CH_1_4_7_A2),
        ("EQ_CH_1_4_8_B0", EQ_CH_1_4_8_B0),
        ("EQ_CH_1_4_8_B1", EQ_CH_1_4_8_B1),
        ("EQ_CH_1_4_8_B2", EQ_CH_1_4_8_B2),
        ("EQ_CH_1_4_8_A1", EQ_CH_1_4_8_A1),
        ("EQ_CH_1_4_8_A2", EQ_CH_1_4_8_A2),
        ("EQ_CH_1_5_1_B0", EQ_CH_1_5_1_B0),
        ("EQ_CH_1_5_1_B1", EQ_CH_1_5_1_B1),
        ("EQ_CH_1_5_1_B2", EQ_CH_1_5_1_B2),
        ("EQ_CH_1_5_1_A1", EQ_CH_1_5_1_A1),
        ("EQ_CH_1_5_1_A2", EQ_CH_1_5_1_A2),
        ("EQ_CH_1_5_2_B0", EQ_CH_1_5_2_B0),
        ("EQ_CH_1_5_2_B1", EQ_CH_1_5_2_B1),
        ("EQ_CH_1_5_2_B2", EQ_CH_1_5_2_B2),
        ("EQ_CH_1_5_2_A1", EQ_CH_1_5_2_A1),
        ("EQ_CH_1_5_2_A2", EQ_CH_1_5_2_A2),
        ("EQ_CH_1_5_3_B0", EQ_CH_1_5_3_B0),
        ("EQ_CH_1_5_3_B1", EQ_CH_1_5_3_B1),
        ("EQ_CH_1_5_3_B2", EQ_CH_1_5_3_B2),
        ("EQ_CH_1_5_3_A1", EQ_CH_1_5_3_A1),
        ("EQ_CH_1_5_3_A2", EQ_CH_1_5_3_A2),
        ("EQ_CH_1_5_4_B0", EQ_CH_1_5_4_B0),
        ("EQ_CH_1_5_4_B1", EQ_CH_1_5_4_B1),
        ("EQ_CH_1_5_4_B2", EQ_CH_1_5_4_B2),
        ("EQ_CH_1_5_4_A1", EQ_CH_1_5_4_A1),
        ("EQ_CH_1_5_4_A2", EQ_CH_1_5_4_A2),
        ("EQ_CH_1_5_5_B0", EQ_CH_1_5_5_B0),
        ("EQ_CH_1_5_5_B1", EQ_CH_1_5_5_B1),
        ("EQ_CH_1_5_5_B2", EQ_CH_1_5_5_B2),
        ("EQ_CH_1_5_5_A1", EQ_CH_1_5_5_A1),
        ("EQ_CH_1_5_5_A2", EQ_CH_1_5_5_A2),
        ("EQ_CH_1_5_6_B0", EQ_CH_1_5_6_B0),
        ("EQ_CH_1_5_6_B1", EQ_CH_1_5_6_B1),
        ("EQ_CH_1_5_6_B2", EQ_CH_1_5_6_B2),
        ("EQ_CH_1_5_6_A1", EQ_CH_1_5_6_A1),
        ("EQ_CH_1_5_6_A2", EQ_CH_1_5_6_A2),
        ("EQ_CH_1_5_7_B0", EQ_CH_1_5_7_B0),
        ("EQ_CH_1_5_7_B1", EQ_CH_1_5_7_B1),
        ("EQ_CH_1_5_7_B2", EQ_CH_1_5_7_B2),
        ("EQ_CH_1_5_7_A1", EQ_CH_1_5_7_A1),
        ("EQ_CH_1_5_7_A2", EQ_CH_1_5_7_A2),
        ("EQ_CH_1_5_8_B0", EQ_CH_1_5_8_B0),
        ("EQ_CH_1_5_8_B1", EQ_CH_1_5_8_B1),
        ("EQ_CH_1_5_8_B2", EQ_CH_1_5_8_B2),
        ("EQ_CH_1_5_8_A1", EQ_CH_1_5_8_A1),
        ("EQ_CH_1_5_8_A2", EQ_CH_1_5_8_A2),
        ("EQ_CH_2_4_1_B0", EQ_CH_2_4_1_B0),
        ("EQ_CH_2_4_1_B1", EQ_CH_2_4_1_B1),
        ("EQ_CH_2_4_1_B2", EQ_CH_2_4_1_B2),
        ("EQ_CH_2_4_1_A1", EQ_CH_2_4_1_A1),
        ("EQ_CH_2_4_1_A2", EQ_CH_2_4_1_A2),
        ("EQ_CH_2_4_2_B0", EQ_CH_2_4_2_B0),
        ("EQ_CH_2_4_2_B1", EQ_CH_2_4_2_B1),
        ("EQ_CH_2_4_2_B2", EQ_CH_2_4_2_B2),
        ("EQ_CH_2_4_2_A1", EQ_CH_2_4_2_A1),
        ("EQ_CH_2_4_2_A2", EQ_CH_2_4_2_A2),
        ("EQ_CH_2_4_3_B0", EQ_CH_2_4_3_B0),
        ("EQ_CH_2_4_3_B1", EQ_CH_2_4_3_B1),
        ("EQ_CH_2_4_3_B2", EQ_CH_2_4_3_B2),
        ("EQ_CH_2_4_3_A1", EQ_CH_2_4_3_A1),
        ("EQ_CH_2_4_3_A2", EQ_CH_2_4_3_A2),
        ("EQ_CH_2_4_4_B0", EQ_CH_2_4_4_B0),
        ("EQ_CH_2_4_4_B1", EQ_CH_2_4_4_B1),
        ("EQ_CH_2_4_4_B2", EQ_CH_2_4_4_B2),
        ("EQ_CH_2_4_4_A1", EQ_CH_2_4_4_A1),
        ("EQ_CH_2_4_4_A2", EQ_CH_2_4_4_A2),
        ("EQ_CH_2_4_5_B0", EQ_CH_2_4_5_B0),
        ("EQ_CH_2_4_5_B1", EQ_CH_2_4_5_B1),
        ("EQ_CH_2_4_5_B2", EQ_CH_2_4_5_B2),
        ("EQ_CH_2_4_5_A1", EQ_CH_2_4_5_A1),
        ("EQ_CH_2_4_5_A2", EQ_CH_2_4_5_A2),
        ("EQ_CH_2_4_6_B0", EQ_CH_2_4_6_B0),
        ("EQ_CH_2_4_6_B1", EQ_CH_2_4_6_B1),
        ("EQ_CH_2_4_6_B2", EQ_CH_2_4_6_B2),
        ("EQ_CH_2_4_6_A1", EQ_CH_2_4_6_A1),
        ("EQ_CH_2_4_6_A2", EQ_CH_2_4_6_A2),
        ("EQ_CH_2_4_7_B0", EQ_CH_2_4_7_B0),
        ("EQ_CH_2_4_7_B1", EQ_CH_2_4_7_B1),
        ("EQ_CH_2_4_7_B2", EQ_CH_2_4_7_B2),
        ("EQ_CH_2_4_7_A1", EQ_CH_2_4_7_A1),
        ("EQ_CH_2_4_7_A2", EQ_CH_2_4_7_A2),
        ("EQ_CH_2_4_8_B0", EQ_CH_2_4_8_B0),
        ("EQ_CH_2_4_8_B1", EQ_CH_2_4_8_B1),
        ("EQ_CH_2_4_8_B2", EQ_CH_2_4_8_B2),
        ("EQ_CH_2_4_8_A1", EQ_CH_2_4_8_A1),
        ("EQ_CH_2_4_8_A2", EQ_CH_2_4_8_A2),
        ("EQ_CH_1_3_1_B0", EQ_CH_1_3_1_B0),
        ("EQ_CH_1_3_1_B1", EQ_CH_1_3_1_B1),
        ("EQ_CH_1_3_1_B2", EQ_CH_1_3_1_B2),
        ("EQ_CH_1_3_1_A1", EQ_CH_1_3_1_A1),
        ("EQ_CH_1_3_1_A2", EQ_CH_1_3_1_A2),
        ("EQ_CH_1_3_2_B0", EQ_CH_1_3_2_B0),
        ("EQ_CH_1_3_2_B1", EQ_CH_1_3_2_B1),
        ("EQ_CH_1_3_2_B2", EQ_CH_1_3_2_B2),
        ("EQ_CH_1_3_2_A1", EQ_CH_1_3_2_A1),
        ("EQ_CH_1_3_2_A2", EQ_CH_1_3_2_A2),
        ("EQ_CH_1_3_3_B0", EQ_CH_1_3_3_B0),
        ("EQ_CH_1_3_3_B1", EQ_CH_1_3_3_B1),
        ("EQ_CH_1_3_3_B2", EQ_CH_1_3_3_B2),
        ("EQ_CH_1_3_3_A1", EQ_CH_1_3_3_A1),
        ("EQ_CH_1_3_3_A2", EQ_CH_1_3_3_A2),
        ("EQ_CH_1_3_4_B0", EQ_CH_1_3_4_B0),
        ("EQ_CH_1_3_4_B1", EQ_CH_1_3_4_B1),
        ("EQ_CH_1_3_4_B2", EQ_CH_1_3_4_B2),
        ("EQ_CH_1_3_4_A1", EQ_CH_1_3_4_A1),
        ("EQ_CH_1_3_4_A2", EQ_CH_1_3_4_A2),
        ("EQ_CH_1_3_5_B0", EQ_CH_1_3_5_B0),
        ("EQ_CH_1_3_5_B1", EQ_CH_1_3_5_B1),
        ("EQ_CH_1_3_5_B2", EQ_CH_1_3_5_B2),
        ("EQ_CH_1_3_5_A1", EQ_CH_1_3_5_A1),
        ("EQ_CH_1_3_5_A2", EQ_CH_1_3_5_A2),
        ("EQ_CH_1_3_6_B0", EQ_CH_1_3_6_B0),
        ("EQ_CH_1_3_6_B1", EQ_CH_1_3_6_B1),
        ("EQ_CH_1_3_6_B2", EQ_CH_1_3_6_B2),
        ("EQ_CH_1_3_6_A1", EQ_CH_1_3_6_A1),
        ("EQ_CH_1_3_6_A2", EQ_CH_1_3_6_A2),
        ("EQ_CH_2_3_1_B0", EQ_CH_2_3_1_B0),
        ("EQ_CH_2_3_1_B1", EQ_CH_2_3_1_B1),
        ("EQ_CH_2_3_1_B2", EQ_CH_2_3_1_B2),
        ("EQ_CH_2_3_1_A1", EQ_CH_2_3_1_A1),
        ("EQ_CH_2_3_1_A2", EQ_CH_2_3_1_A2),
        ("EQ_CH_2_3_2_B0", EQ_CH_2_3_2_B0),
        ("EQ_CH_2_3_2_B1", EQ_CH_2_3_2_B1),
        ("EQ_CH_2_3_2_B2", EQ_CH_2_3_2_B2),
        ("EQ_CH_2_3_2_A1", EQ_CH_2_3_2_A1),
        ("EQ_CH_2_3_2_A2", EQ_CH_2_3_2_A2),
        ("EQ_CH_2_3_3_B0", EQ_CH_2_3_3_B0),
        ("EQ_CH_2_3_3_B1", EQ_CH_2_3_3_B1),
        ("EQ_CH_2_3_3_B2", EQ_CH_2_3_3_B2),
        ("EQ_CH_2_3_3_A1", EQ_CH_2_3_3_A1),
        ("EQ_CH_2_3_3_A2", EQ_CH_2_3_3_A2),
        ("EQ_CH_2_3_4_B0", EQ_CH_2_3_4_B0),
        ("EQ_CH_2_3_4_B1", EQ_CH_2_3_4_B1),
        ("EQ_CH_2_3_4_B2", EQ_CH_2_3_4_B2),
        ("EQ_CH_2_3_4_A1", EQ_CH_2_3_4_A1),
        ("EQ_CH_2_3_4_A2", EQ_CH_2_3_4_A2),
        ("EQ_CH_2_3_5_B0", EQ_CH_2_3_5_B0),
        ("EQ_CH_2_3_5_B1", EQ_CH_2_3_5_B1),
        ("EQ_CH_2_3_5_B2", EQ_CH_2_3_5_B2),
        ("EQ_CH_2_3_5_A1", EQ_CH_2_3_5_A1),
        ("EQ_CH_2_3_5_A2", EQ_CH_2_3_5_A2),
        ("EQ_CH_2_3_6_B0", EQ_CH_2_3_6_B0),
        ("EQ_CH_2_3_6_B1", EQ_CH_2_3_6_B1),
        ("EQ_CH_2_3_6_B2", EQ_CH_2_3_6_B2),
        ("EQ_CH_2_3_6_A1", EQ_CH_2_3_6_A1),
        ("EQ_CH_2_3_6_A2", EQ_CH_2_3_6_A2),
        ("EQ_CH_2_2_1_B0", EQ_CH_2_2_1_B0),
        ("EQ_CH_2_2_1_B1", EQ_CH_2_2_1_B1),
        ("EQ_CH_2_2_1_B2", EQ_CH_2_2_1_B2),
        ("EQ_CH_2_2_1_A1", EQ_CH_2_2_1_A1),
        ("EQ_CH_2_2_1_A2", EQ_CH_2_2_1_A2),
        ("EQ_CH_2_2_2_B0", EQ_CH_2_2_2_B0),
        ("EQ_CH_2_2_2_B1", EQ_CH_2_2_2_B1),
        ("EQ_CH_2_2_2_B2", EQ_CH_2_2_2_B2),
        ("EQ_CH_2_2_2_A1", EQ_CH_2_2_2_A1),
        ("EQ_CH_2_2_2_A2", EQ_CH_2_2_2_A2),
        ("EQ_CH_2_2_3_B0", EQ_CH_2_2_3_B0),
        ("EQ_CH_2_2_3_B1", EQ_CH_2_2_3_B1),
        ("EQ_CH_2_2_3_B2", EQ_CH_2_2_3_B2),
        ("EQ_CH_2_2_3_A1", EQ_CH_2_2_3_A1),
        ("EQ_CH_2_2_3_A2", EQ_CH_2_2_3_A2),
        ("EQ_CH_2_2_4_B0", EQ_CH_2_2_4_B0),
        ("EQ_CH_2_2_4_B1", EQ_CH_2_2_4_B1),
        ("EQ_CH_2_2_4_B2", EQ_CH_2_2_4_B2),
        ("EQ_CH_2_2_4_A1", EQ_CH_2_2_4_A1),
        ("EQ_CH_2_2_4_A2", EQ_CH_2_2_4_A2),
        ("EQ_CH_2_2_5_B0", EQ_CH_2_2_5_B0),
        ("EQ_CH_2_2_5_B1", EQ_CH_2_2_5_B1),
        ("EQ_CH_2_2_5_B2", EQ_CH_2_2_5_B2),
        ("EQ_CH_2_2_5_A1", EQ_CH_2_2_5_A1),
        ("EQ_CH_2_2_5_A2", EQ_CH_2_2_5_A2),
        ("EQ_CH_2_2_6_B0", EQ_CH_2_2_6_B0),
        ("EQ_CH_2_2_6_B1", EQ_CH_2_2_6_B1),
        ("EQ_CH_2_2_6_B2", EQ_CH_2_2_6_B2),
        ("EQ_CH_2_2_6_A1", EQ_CH_2_2_6_A1),
        ("EQ_CH_2_2_6_A2", EQ_CH_2_2_6_A2),
        ("EQ_CH_1_2_1_B0", EQ_CH_1_2_1_B0),
        ("EQ_CH_1_2_1_B1", EQ_CH_1_2_1_B1),
        ("EQ_CH_1_2_1_B2", EQ_CH_1_2_1_B2),
        ("EQ_CH_1_2_1_A1", EQ_CH_1_2_1_A1),
        ("EQ_CH_1_2_1_A2", EQ_CH_1_2_1_A2),
        ("EQ_CH_1_2_2_B0", EQ_CH_1_2_2_B0),
        ("EQ_CH_1_2_2_B1", EQ_CH_1_2_2_B1),
        ("EQ_CH_1_2_2_B2", EQ_CH_1_2_2_B2),
        ("EQ_CH_1_2_2_A1", EQ_CH_1_2_2_A1),
        ("EQ_CH_1_2_2_A2", EQ_CH_1_2_2_A2),
        ("EQ_CH_1_2_3_B0", EQ_CH_1_2_3_B0),
        ("EQ_CH_1_2_3_B1", EQ_CH_1_2_3_B1),
        ("EQ_CH_1_2_3_B2", EQ_CH_1_2_3_B2),
        ("EQ_CH_1_2_3_A1", EQ_CH_1_2_3_A1),
        ("EQ_CH_1_2_3_A2", EQ_CH_1_2_3_A2),
        ("EQ_CH_1_2_4_B0", EQ_CH_1_2_4_B0),
        ("EQ_CH_1_2_4_B1", EQ_CH_1_2_4_B1),
        ("EQ_CH_1_2_4_B2", EQ_CH_1_2_4_B2),
        ("EQ_CH_1_2_4_A1", EQ_CH_1_2_4_A1),
        ("EQ_CH_1_2_4_A2", EQ_CH_1_2_4_A2),
        ("EQ_CH_1_2_5_B0", EQ_CH_1_2_5_B0),
        ("EQ_CH_1_2_5_B1", EQ_CH_1_2_5_B1),
        ("EQ_CH_1_2_5_B2", EQ_CH_1_2_5_B2),
        ("EQ_CH_1_2_5_A1", EQ_CH_1_2_5_A1),
        ("EQ_CH_1_2_5_A2", EQ_CH_1_2_5_A2),
        ("EQ_CH_1_2_6_B0", EQ_CH_1_2_6_B0),
        ("EQ_CH_1_2_6_B1", EQ_CH_1_2_6_B1),
        ("EQ_CH_1_2_6_B2", EQ_CH_1_2_6_B2),
        ("EQ_CH_1_2_6_A1", EQ_CH_1_2_6_A1),
        ("EQ_CH_1_2_6_A2", EQ_CH_1_2_6_A2),
        ("MULT_CTRL_DEL_GROW_ALG_4", MULT_CTRL_DEL_GROW_ALG_4),
        ("MULT_CTRL_DEL_GROW_ALG_3", MULT_CTRL_DEL_GROW_ALG_3),
        ("MULT_CTRL_DEL_GROW_ALG_1", MULT_CTRL_DEL_GROW_ALG_1),
        ("MULT_CTRL_DEL_GROW_ALG_2", MULT_CTRL_DEL_GROW_ALG_2),
        ("GAIN_1940_ALG_NS6", GAIN_1940_ALG_NS6),
        ("GAIN_1940_ALG_NS3", GAIN_1940_ALG_NS3),
        ("GAIN_1940_ALG_NS5", GAIN_1940_ALG_NS5),
        ("GAIN_1940_ALG_NS4", GAIN_1940_ALG_NS4),
        ("MUTE_NO_SLEW_ALG_5MUTE", MUTE_NO_SLEW_ALG_5MUTE),
        ("MUTE_NO_SLEW_ALG_3MUTE", MUTE_NO_SLEW_ALG_3MUTE),
        ("MUTE_NO_SLEW_ALG_6MUTE", MUTE_NO_SLEW_ALG_6MUTE),
        ("MUTE_NO_SLEW_ALG_4MUTE", MUTE_NO_SLEW_ALG_4MUTE),
        ("EQ1940_INVERT_4GAIN", EQ1940_INVERT_4GAIN),
        ("EQ1940_INVERT_5GAIN", EQ1940_INVERT_5GAIN),
        ("EQ1940_INVERT_3GAIN", EQ1940_INVERT_3GAIN),
        ("EQ1940_INVERT_6GAIN", EQ1940_INVERT_6GAIN),
        ("EXT_SW_GAIN_DB_1STEP", EXT_SW_GAIN_DB_1STEP),
        ("STEREO_DEMUX_SLEW_10", STEREO_DEMUX_SLEW_10),
        ("STEREO_DEMUX_SLEW_11", STEREO_DEMUX_SLEW_11),
        ("SINGLE_CTRL_MIXER_NEW19401", SINGLE_CTRL_MIXER_NEW19401),
        ("ST_MUX_SW_SLEW_1COEFFNAME", ST_MUX_SW_SLEW_1COEFFNAME),
        ("STEREOMUX_194_0NS_20", STEREOMUX_194_0NS_20),
        ("STEREOMUX_194_0NS_21", STEREOMUX_194_0NS_21),
        ("STEREOMUX_194_0NS_22", STEREOMUX_194_0NS_22),
        (
            "DC_BLOCK_ALG_DOUBLE_PREC_1POLE",
            DC_BLOCK_ALG_DOUBLE_PREC_1POLE,
        ),
        (
            "DC_BLOCK_ALG_DOUBLE_PREC_2POLE",
            DC_BLOCK_ALG_DOUBLE_PREC_2POLE,
        ),
        ("MONO_ENVELOPE_PEAK_ALG_1HOLD", MONO_ENVELOPE_PEAK_ALG_1HOLD),
        (
            "MONO_ENVELOPE_PEAK_ALG_1DECAY",
            MONO_ENVELOPE_PEAK_ALG_1DECAY,
        ),
        ("MONO_ENVELOPE_PEAK_ALG_2HOLD", MONO_ENVELOPE_PEAK_ALG_2HOLD),
        (
            "MONO_ENVELOPE_PEAK_ALG_2DECAY",
            MONO_ENVELOPE_PEAK_ALG_2DECAY,
        ),
    ];
}
#[allow(unused_imports)]
use sym::*;
pub const DEVICE: Device = Device {
    product_name: "MiniDSP 2x4",
    sources: &[Toslink, Spdif],
    inputs: &[],
    outputs: &[],
    fir_max_taps: 0,
    internal_sampling_rate: 48000,
    dialect: Dialect {
        addr_encoding: AddrEncoding::AddrLen2,
        float_encoding: FloatEncoding::FixedPoint,
    },
    #[cfg(feature = "symbols")]
    symbols: SYMBOLS,
};
