FROM rust:1.64.0-buster
RUN rustup target add arm-unknown-linux-gnueabihf
RUN cargo install cargo-deb
ADD . /src

RUN mkdir /build && \
    mkdir /pi-tools && \
    curl -L https://github.com/raspberrypi/tools/archive/648a6eeb1e3c2b40af4eb34d88941ee0edeb3e9a.tar.gz | tar xz --strip-components 1 -C /pi-tools
