//! ALSA softvol configuration generator
//!
//! Creates ALSA configuration to enable software volume control on USB audio cards
//! that don't support user-created control elements.

use std::fs;
use std::path::Path;

/// Generate ALSA softvol configuration for a MiniDSP device
///
/// Creates a configuration snippet that can be added to ~/.asoundrc or /etc/asound.conf
///
/// Note: The control is created on card 0 (which supports softvol)
/// Audio can route to any device specified by output_device
pub fn generate_softvol_config(
    device_name: &str,
    card_number: u32,
    control_name: &str,
    output_device: &str,
) -> String {
    format!(
        r#"# MiniDSP Software Volume Control for {device_name}
# This creates a virtual volume control on card 0
# Audio routes to {output_device} while volume syncs with MiniDSP hardware
# Generated by minidsp-rs daemon

pcm.minidsp_{card_number}_softvol {{
    type softvol
    slave.pcm "{output_device}"
    control {{
        name "{control_name}"
        card 0
    }}
    min_dB -127.0
    max_dB 0.0
    resolution 256
}}

# Optional: Set as default output
# Uncomment to make this the system default
# pcm.!default {{
#     type plug
#     slave.pcm "minidsp_{card_number}_softvol"
# }}
"#
    )
}

/// Write ALSA softvol configuration to user's asoundrc
///
/// Creates or appends to ~/.asoundrc with the softvol configuration
pub fn write_user_asoundrc(
    device_name: &str,
    card_number: u32,
    control_name: &str,
    output_device: &str,
) -> anyhow::Result<()> {
    let home_dir = std::env::var("HOME").or_else(|_| std::env::var("USERPROFILE"))?;
    let asoundrc_path = Path::new(&home_dir).join(".asoundrc");

    let config = generate_softvol_config(device_name, card_number, control_name, output_device);

    // Check if file exists and contains our config already
    if asoundrc_path.exists() {
        let existing = fs::read_to_string(&asoundrc_path)?;
        if existing.contains(&format!("pcm.minidsp_{}_softvol", card_number)) {
            log::info!("ALSA softvol config already exists in ~/.asoundrc");
            return Ok(());
        }
        // Append to existing file
        let updated = format!("{}\n\n{}", existing, config);
        fs::write(&asoundrc_path, updated)?;
        log::info!("Appended ALSA softvol config to ~/.asoundrc");
    } else {
        // Create new file
        fs::write(&asoundrc_path, config)?;
        log::info!("Created ~/.asoundrc with ALSA softvol config");
    }

    Ok(())
}

/// Check if softvol control exists and is accessible
///
/// Returns true if the control can be found via ALSA mixer API
#[cfg(target_os = "linux")]
pub fn check_softvol_exists(card_name: &str, control_name: &str) -> bool {
    use alsa::mixer::{Mixer, SelemId};

    match Mixer::new(card_name, false) {
        Ok(mixer) => {
            let selem_id = SelemId::new(control_name, 0);
            mixer.find_selem(&selem_id).is_some()
        }
        Err(_) => false,
    }
}

#[cfg(not(target_os = "linux"))]
pub fn check_softvol_exists(_card_name: &str, _control_name: &str) -> bool {
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_config() {
        let config = generate_softvol_config("DDRC-24", 2, "DDRC-24 Volume", "hw:0");
        assert!(config.contains("pcm.minidsp_2_softvol"));
        assert!(config.contains("hw:0"));
        assert!(config.contains("DDRC-24 Volume"));
        assert!(config.contains("-127.0"));
    }
}
